CREATE DATABASE ALEXAMARA;

CREATE TABLE MARINA (
	
	MARINA_NUM CHAR(4) NOT NULL PRIMARY KEY,
	NAME CHAR(20) NOT NULL,
	ADDRESS CHAR(15),
	CITY CHAR(15),
	STATE CHAR(2),
	ZIP CHAR(5));

CREATE TABLE MARINA_SLIP (

	SLIP_ID DECIMAL(4,0) NOT NULL PRIMARY KEY,
	MARINA_NUM CHAR(4),
	SLIP_NUM CHAR(4),
	LENGTH DECIMAL(4,0),
	RENTAL_FEE DECIMAL(8,2),
	BOAT_NAME CHAR(50),
	BOAT_TYPE CHAR(50),
	OWNER_NUM CHAR(4));

CREATE TABLE OWNER (

	OWNER_NUM CHAR(4) NOT NULL PRIMARY KEY,
	LAST_NAME CHAR(50),
	FIRST_NAME CHAR(20),
	ADDRESS CHAR(15),
	CITY CHAR(15),
	STATE CHAR(2),
	ZIP CHAR(5));

CREATE TABLE SERVICE_CATEGORY (

	CATEGORY_NUM DECIMAL(4,0) NOT NULL PRIMARY KEY,
	CATEGORY_DESCRIPTION CHAR(255));

CREATE TABLE SERVICE_REQUEST (

	SERVICE_ID DECIMAL(4,0) NOT NULL PRIMARY KEY,
	SLIP_ID DECIMAL(4,0),
	CATEGORY_NUM DECIMAL(4,0),
	DESCRIPTION CHAR(255),
	STATUS CHAR(255),
	EST_HOURS DECIMAL(4,2),
	SPENT_HOURS DECIMAL(4,2),
	NEXT_SERVICE_DATE DATE);